captainVersion: 4
version: '3'
services:
    $$cap_appname:
        container_name: docklogkeeper
        image: nightlord189/docklogkeeper:$$cap_version
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $$cap_appname-data:/logs
        ports:
            - 3010:3010
        environment:
            PASSWORD: $$cap_password
        caproverExtra:
            containerHttpPort: '3010'
caproverOneClickApp:
    variables:
        - id: $$cap_version
          label: Version
          defaultValue: '1.0.3'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/nightlord189/docklogkeeper/tags
        - id: $$cap_password
          label: Password
          defaultValue: $$cap_gen_random_hex(16)
          description: Admin password
    instructions:
        start: |-
            Simple Docker log viewer. DockLogKeeper offers a streamlined approach to viewing Docker logs. 
            It persistently stores logs in a local SQLite database, ensuring both real-time and historical logs are readily accessible.
        end: |-
            DockLogKeeper is deployed and available at `$$cap_appname.$$cap_root_domain`. Default username is admin.
    displayName: DockLogKeeper
    isOfficial: true
    description: Simple Docker log viewer, persistently stores logs in a local SQLite database, ensuring both real-time and historical logs are readily accessible.
    documentation: Taken from https://github.com/nightlord189/docklogkeeper
