name: Publish One Click Apps

on:
  push:
    branches: [master]
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci

      - run: npm run formatter-write && npm run build

      - name: GitHub Pages Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          FOLDER: dist
